@extends('hyde::layouts.app')
@php($title = "The Deep Dive Podcast: HydePHP")
@section('content')

    <main class="mx-auto max-w-7xl py-16 px-8">
        <h1 class="text-center text-3xl font-bold mb-8">The Deep Dive Podcast: HydePHP</h1>

        <div class="bg-white shadow-md rounded-lg p-6 mb-8">
            <h2 class="text-2xl font-semibold mb-4">Listen to Our AI-Generated Podcast</h2>
            <p class="mb-4">Explore the world of HydePHP in this unique, AI-generated podcast episode. Experience a blend of technology and creativity as we dive deep into the features and benefits of this innovative static site generator.</p>

            <div id="player" class="mb-4"></div>

            <p class="text-sm text-gray-600 italic">Note: This podcast episode is entirely generated by AI, showcasing the potential of artificial intelligence in content creation.</p>
        </div>

        <div class="bg-gray-100 rounded-lg p-6">
            <h2 class="text-xl font-semibold mb-4">About This AI-Generated Podcast</h2>
            <p class="mb-2">This podcast episode was created using advanced AI technology from NotebookML. Here's what makes it special:</p>
            <ul class="list-disc list-inside mb-4">
                <li>Content is 100% AI-generated, based on information about HydePHP</li>
                <li>Demonstrates the capabilities of AI in producing engaging, informative content</li>
                <li>Offers a unique perspective on HydePHP's features and benefits</li>
            </ul>
            <p>While this content is AI-generated, it reflects our commitment to exploring innovative ways to share information about HydePHP. We hope you enjoy this blend of technology and creativity!</p>
        </div>
    </main>

@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/shikwasa@2.2.0/dist/shikwasa.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/shikwasa@2.2.0/dist/style.css">

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const player = new Shikwasa.Player({
                container: () => document.getElementById('player'),
                audio: {
                    title: 'The Deep Dive: HydePHP',
                    artist: 'AI-Generated Podcast',
                    cover: 'https://hydephp.com/favicon.ico', // Replace with actual cover image
                    src: "{{ asset('podcast/introduction.wav') }}",
                },
                chapters: [
                    { title: 'Introduction', startTime: 0, endTime: 60 },
                    { title: 'Features of HydePHP', startTime: 60, endTime: 180 },
                    { title: 'Benefits and Use Cases', startTime: 180, endTime: 300 },
                    { title: 'Conclusion', startTime: 300, endTime: 360 },
                ],
                themeColor: '#4A5568',
            });

            // Load and display transcript
            fetch("{{ asset('podcast/introduction.srt') }}")
                .then(response => response.text())
                .then(srt => {
                    const transcriptDiv = document.createElement('div');
                    transcriptDiv.className = 'mt-4 p-4 bg-gray-50 rounded overflow-y-auto max-h-60';
                    transcriptDiv.innerHTML = '<h3 class="font-semibold mb-2">Transcript</h3>' +
                        '<p class="text-sm">' + srt.replace(/\n/g, '<br>') + '</p>';
                    document.getElementById('player').after(transcriptDiv);
                });
        });
    </script>
@endpush