<aside class="w-full lg:w-1/2 p-4 m-4 mt-8 prose" data-aos="fade-left">
	<table class="border mdl-data-table mdl-js-data-table aVTXAb-BeDmAc-LJTIlf-jyrRxf" style="">
		<thead>
			<tr>
				<th colspan="2">
					<details>
						<summary class="cursor-pointer px-3 pt-1"> Data parsed by <a
								href="https://validator.schema.org/">schema.org</a> </summary>
						<p class="font-normal px-4"> <strong>About the table:</strong> This table is one generated by
							the Schema.org Validator and shows the article data parsed by their system. This kind of
							content can show up in smart cards and search results and may help improve your SEO. </p>
					</details>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr begin="0" end="4230">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 34px; font-weight: bold">@type</div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div>Article</div>
				</td>
			</tr>
			<tr begin="0" end="4230">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 34px; font-weight: bold">@id</div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div>http://schema.org/post-article</div>
				</td>
			</tr>
			<tr begin="114" end="174">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 34px; font-weight: bold">identifier</div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div>alice-in-wonderland</div>
				</td>
			</tr>
			<tr begin="242" end="367">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 34px; font-weight: bold">headline</div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div>Alice's Adventures in Wonderland</div>
				</td>
			</tr>
			<tr begin="513" end="660">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 34px; font-weight: bold">dateCreated</div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div>1865-11-18T18:52:00</div>
				</td>
			</tr>
			<tr begin="513" end="660">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 34px; font-weight: bold">datePublished</div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div>1865-11-18T18:52:00</div>
				</td>
			</tr>
			<tr begin="1028" end="4207">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 34px; font-weight: bold">articleBody</div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div><span title="Demo content truncated for spacing">Alice was beginning to get very tired of
							sitting by her sister on the bank, and of having nothing to do...</span></div>
				</td>
			</tr>
			<tr begin="719" end="909">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 34px; font-weight: bold"><span
							title="Merged for brevity">author/publisher</span></div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div></div>
				</td>
			</tr>
			<tr begin="719" end="909">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 58px; font-weight: bold">@type</div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div>Person</div>
				</td>
			</tr>
			<tr begin="832" end="874">
				<td class="mdl-data-table__cell--non-numeric V1ur5d-jyrRxf-eEDwDf">
					<div style="display: inline-block; padding-left: 58px; font-weight: bold">name</div>
				</td>
				<td class="mdl-data-table__cell--non-numeric lTBxed-jyrRxf-eEDwDf">
					<div>Lewis Carroll</div>
				</td>
			</tr>
		</tbody>
	</table>
</aside>