name: Test Pull Request

on:
  pull_request:
    branches: [ master, upcoming ]

jobs:
  can-build-site:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Update config
      run: |
        echo output_directory: _site > hyde.yml

    - name: Install composer dependencies
      run: composer install

    - name: Output debug information
      run: |
        php hyde --version
        php hyde debug

    - name: Run the Hyde Builder
      run: php hyde build --pretty-urls --no-interaction

    - name: Create docs redirect
      run: echo '<meta http-equiv="refresh" content="0;url=/docs/1.x" />' > _site/docs/index.html

    - name: Assert site is built
      run: |
        # Define the directory to check
        SITE_DIR="_site"
        
        # Check if the directory exists
        if [ ! -d "$SITE_DIR" ]; then
          echo "Error: $SITE_DIR directory does not exist."
          exit 1
        fi
        
        # Check if there are any HTML files in the directory
        HTML_FILES=$(find "$SITE_DIR" -name "*.html")
        
        if [ -z "$HTML_FILES" ]; then
          echo "Error: No HTML files found in $SITE_DIR."
          exit 1
        fi
      
        # If checks pass
        echo "Success: Static site built in $SITE_DIR."
        exit 0

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: _site
